version: '2'

services:

  postgres-tenpo:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: tenpo
      POSTGRES_DB: tenpo_challenge

  tenpo:
    image: 'tenpo:challenge'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: challenge
    depends_on:
      - postgres-tenpo
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpo_challenge
      - SPRING_DATASOURCE_USERNAME=tenpo
      - SPRING_DATASOURCE_PASSWORD=tenpo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



