version: '2'

services:
  tenpo:
    image: 'tenpo:challenge'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: challenge
    depends_on:
      - postgres-tenpo


  postgres-tenpo:
    image: postgres:14.2
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= tenpo
      - POSTGRES_PASSWORD= 1234
      - POSTGRES_DB= tenpo_challenge
